package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class AdminController {
	@FXML
	private Button users;
	@FXML
	private Button orders;
	@FXML
	private Button complaints;

	// Event Listener on Button[#users].onAction
	@FXML
	public void manage_users(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#orders].onAction
	@FXML
	public void view_all_orders(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#complaints].onAction
	@FXML
	public void resolve_complaints(ActionEvent event) {
		// TODO Autogenerated
	}
}
