package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class CustomerController {
	@FXML
	private Button items;
	@FXML
	private Button services;
	@FXML
	private Button active_orders;
	@FXML
	private Button active_services;
	@FXML
	private Button order_history;
	// Event Listener on Button[#items].onAction
	@FXML
	public void gotoItems(ActionEvent event) throws IOException {
		// TODO Autogenerated
		 Stage stage = (Stage) items.getScene().getWindow(); stage.close(); 
		 Stage primaryStage = new Stage(); 
		 Parent root = FXMLLoader.load(getClass().getResource("cust_items.fxml")); 
		 Scene scene = new Scene(root);
		 //scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm()); 
		 primaryStage.setScene(scene); primaryStage.show();
	}
	// Event Listener on Button[#services].onAction
	@FXML
	public void gotoServices(ActionEvent event) throws IOException {
		// TODO Autogenerated
		 Stage stage = (Stage) services.getScene().getWindow(); stage.close(); 
		 Stage primaryStage = new Stage(); 
		 Parent root = FXMLLoader.load(getClass().getResource("cust_services.fxml")); 
		 Scene scene = new Scene(root);
		 //scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm()); 
		 primaryStage.setScene(scene); primaryStage.show();
	}
	// Event Listener on Button[#active_orders].onAction
	@FXML
	public void seeActiveOrders(ActionEvent event) throws IOException {
		// TODO Autogenerated
		 Stage stage = (Stage) active_orders.getScene().getWindow(); stage.close(); 
		 Stage primaryStage = new Stage(); 
		 Parent root = FXMLLoader.load(getClass().getResource("active_orders.fxml")); 
		 Scene scene = new Scene(root);
		 //scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm()); 
		 primaryStage.setScene(scene); primaryStage.show();
	}
	// Event Listener on Button[#active_services].onAction
	@FXML
	public void seeActiveServices(ActionEvent event) throws IOException {
		// TODO Autogenerated
		 Stage stage = (Stage) active_services.getScene().getWindow(); stage.close(); 
		 Stage primaryStage = new Stage(); 
		 Parent root = FXMLLoader.load(getClass().getResource("active_services.fxml")); 
		 Scene scene = new Scene(root);
		 //scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm()); 
		 primaryStage.setScene(scene); primaryStage.show();
	}
	// Event Listener on Button[#order_history].onAction
	@FXML
	public void gotoHistory(ActionEvent event) throws IOException {
		// TODO Autogenerated
		 Stage stage = (Stage) order_history.getScene().getWindow(); stage.close(); 
		 Stage primaryStage = new Stage(); 
		 Parent root = FXMLLoader.load(getClass().getResource("order_history.fxml")); 
		 Scene scene = new Scene(root);
		 //scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm()); 
		 primaryStage.setScene(scene); primaryStage.show();
	}
}
