package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.DatePicker;
import javafx.stage.Stage;

public class date_pickerController {
	@FXML
	private DatePicker date;
	@FXML
	private Button next;

	// Event Listener on Button[#next].onAction
	@FXML
	public void proceed(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Stage stage = (Stage) next.getScene().getWindow(); stage.close(); 
		Stage primaryStage = new Stage(); 
  		 Parent root = FXMLLoader.load(getClass().getResource("cust_services.fxml")); 
  		 Scene scene = new Scene(root);
  		 //scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm()); 
  		 primaryStage.setScene(scene); primaryStage.show();

	}
}
