package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class EvaluatorController {
	@FXML
	private Button requests;
	@FXML
	private Button services;
	@FXML
	private Button eval;

	// Event Listener on Button[#requests].onAction
	@FXML
	public void view_requests(ActionEvent event) throws IOException {
		// TODO Autogenerated
		// TODO Autogenerated
		 Stage stage = (Stage) requests.getScene().getWindow(); stage.close(); 
		 Stage primaryStage = new Stage(); 
		 Parent root = FXMLLoader.load(getClass().getResource("view_requests.fxml")); 
		 Scene scene = new Scene(root);
		 //scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm()); 
		 primaryStage.setScene(scene); primaryStage.show();
	}
	// Event Listener on Button[#services].onAction
	@FXML
	public void list_services(ActionEvent event) throws IOException {
		// TODO Autogenerated
		// TODO Autogenerated
		 Stage stage = (Stage) requests.getScene().getWindow(); stage.close(); 
		 Stage primaryStage = new Stage(); 
		 Parent root = FXMLLoader.load(getClass().getResource("list_services.fxml")); 
		 Scene scene = new Scene(root);
		 //scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm()); 
		 primaryStage.setScene(scene); primaryStage.show();
	}
	// Event Listener on Button[#eval].onAction
	@FXML
	public void submit_eval(ActionEvent event) throws IOException {
		// TODO Autogenerated
		// TODO Autogenerated
		 Stage stage = (Stage) requests.getScene().getWindow(); stage.close(); 
		 Stage primaryStage = new Stage(); 
		 Parent root = FXMLLoader.load(getClass().getResource("sumbit_evaluation.fxml")); 
		 Scene scene = new Scene(root);
		 //scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm()); 
		 primaryStage.setScene(scene); primaryStage.show();
	}
}
