package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class RefurbisherController {
	@FXML
	private Button requests;
	@FXML
	private Button services;

	// Event Listener on Button[#requests].onAction
	@FXML
	public void view_requests(ActionEvent event) throws IOException {
		// TODO Autogenerated
		 Stage stage = (Stage) requests.getScene().getWindow();
		 stage.close();
		 Stage primaryStage = new Stage();
		 Parent root = FXMLLoader.load(getClass().getResource("view_requests_refurb.fxml")); 
		 Scene scene = new Scene(root);
		 //scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm()); 
		 primaryStage.setScene(scene); primaryStage.show();
	}
	// Event Listener on Button[#services].onAction
	@FXML
	public void list_services(ActionEvent event) throws IOException {
		// TODO Autogenerated
		 Stage stage = (Stage) requests.getScene().getWindow();
		 stage.close();
		 Stage primaryStage = new Stage();
		 Parent root = FXMLLoader.load(getClass().getResource("list_services.fxml")); 
		 Scene scene = new Scene(root);
		 //scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm()); 
		 primaryStage.setScene(scene); primaryStage.show();
	}
	public void see_listed_services(ActionEvent event) throws IOException {
		// TODO Autogenerated
		 Stage stage = (Stage) requests.getScene().getWindow();
		 stage.close();
		 Stage primaryStage = new Stage();
		 Parent root = FXMLLoader.load(getClass().getResource("all_listed_services.fxml")); 
		 Scene scene = new Scene(root);
		 //scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm()); 
		 primaryStage.setScene(scene); primaryStage.show();
	}
}
