package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class RetailerController {
	@FXML
	private Button items;
	@FXML
	private Button l_items;
	@FXML
	private Button discounts;
	@FXML
	private Button ratings;
	@FXML
	private Button inventory;


	// Event Listener on Button[#l_items].onAction
	@FXML
	public void list_items(ActionEvent event) {
		try {
	        // Load the FXML file
	        FXMLLoader loader = new FXMLLoader(getClass().getResource("add_item.fxml"));
	        Parent root = loader.load();
	        
	        // Create a new stage (window)
	        Stage stage = new Stage();
	        stage.setScene(new Scene(root));
	        
	        // Set title for the new window (optional)
	        stage.setTitle("Add Item");
	        
	        // Show the new window
	        stage.show();
	        
	    } catch (IOException e) {
	        e.printStackTrace();
	        // Handle the error (maybe show an alert or log the error)
	    }
	}
	// Event Listener on Button[#discounts].onAction
	@FXML
	public void view_listed_items(ActionEvent event) throws IOException {
		// TODO Autogenerated
		 Stage stage = (Stage) items.getScene().getWindow(); stage.close(); 
		 Stage primaryStage = new Stage(); 
		 Parent root = FXMLLoader.load(getClass().getResource("all_Listed_items.fxml")); 
		 Scene scene = new Scene(root);
		 //scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm()); 
		 primaryStage.setScene(scene); primaryStage.show();
	}
	// Event Listener on Button[#l_items].onAction
	
	// Event Listener on Button[#discounts].onAction
	@FXML
	public void give_discounts(ActionEvent event) throws IOException {
		// TODO Autogenerated
		 Stage stage = (Stage) items.getScene().getWindow(); stage.close(); 
		 Stage primaryStage = new Stage(); 
		 Parent root = FXMLLoader.load(getClass().getResource("add_discounts.fxml")); 
		 Scene scene = new Scene(root);
		 //scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm()); 
		 primaryStage.setScene(scene); primaryStage.show();
	}
	// Event Listener on Button[#ratings].onAction
	@FXML
	public void view_ratings(ActionEvent event) throws IOException {
		// TODO Autogenerated
		 Stage stage = (Stage) items.getScene().getWindow(); stage.close(); 
		 Stage primaryStage = new Stage(); 
		 Parent root = FXMLLoader.load(getClass().getResource("view_ratings.fxml")); 
		 Scene scene = new Scene(root);
		 //scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm()); 
		 primaryStage.setScene(scene); primaryStage.show();
	}
	// Event Listener on Button[#inventory].onAction
	@FXML
	public void update_inventory(ActionEvent event) {
		// TODO Autogenerated
	}}
