package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

public class view_requests_refurbController {
	@FXML
	private TableView table;
	@FXML
	private Button next;
	@FXML
	private Button clear;
	@FXML
	private Button back;

	// Event Listener on Button[#next].onAction
	@FXML
	public void proceed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#clear].onAction
	@FXML
	public void clear_selection(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#back].onAction
	@FXML
	public void goBack(ActionEvent event) {
		// TODO Autogenerated
	}
}
