package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.TableView;
import javafx.scene.control.Alert.AlertType;
import javafx.stage.Stage;

public class view_requestsController {
	@FXML
	private TableView table;
	@FXML
	private Button next;
	@FXML
	private Button clear;
	@FXML
	private Button back;

	// Event Listener on Button[#next].onAction
	@FXML
	public void proceed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#clear].onAction
	@FXML
	public void clear_selection(ActionEvent event) {
		// TODO Autogenerated
        // Clear all selected rows in the TableView
        table.getSelectionModel().clearSelection();
        
        // Show alert when selections are cleared
        Alert alert = new Alert(AlertType.INFORMATION);
        alert.setTitle("Selection Cleared");
        alert.setHeaderText(null);
        alert.setContentText("All selections have been cleared.");
        alert.showAndWait();
	}
	// Event Listener on Button[#back].onAction
	@FXML
	public void goBack(ActionEvent event) throws IOException {
		// TODO Autogenerated
		// handle go back according to evaluator or refurbisher fxml
//		 Stage stage = (Stage) back.getScene().getWindow(); stage.close(); 
//		 Stage primaryStage = new Stage(); 
//		 Parent root = FXMLLoader.load(getClass().getResource("Refurbisher.fxml")); 
//		 Scene scene = new Scene(root);
//		 //scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm()); 
//		 primaryStage.setScene(scene); primaryStage.show();
	}
}
